language: python
python: 3.7
sudo: false

env:
  global:
    - secure: "uZfSLEQBM9f5dgIMfBXkaKY+pUt1/bm59wS1p9W9XTSEf1zB43iqcjCe3fL4/WRJr/y6l0btI6uhzQGt3br43zKmBN7Q0PzC/ZbfxBbd18xkCiqVGGHTadPika5Ig/NVlA+9u7f2QPL3mTspD7uBWm8/xKtsvbK3z6x13lxWfiJc5H5N4xD+nwauzsjU1G+jVq/3xoIQMOfXKuOPezokhaEXWVF9oS8xiFlFFCNrI9yE/+DI0l+uXzqzs5zi09GG4Eq1Z6jFosIHqBpz3d/Q2etvteIoFXJ3Ss3FytHIk0Lq/G48GeNOXynWBPBUHkevXd5/clb5iEZaku+MInc1rzvyUR8SZEJLdjfgmkxaNbmdSowNBQ4wAoenLmU2BfNHmYNoOrpOthBOXV6UqXTYg1vyByElqU4nnRQxaFOlia2Yks8XzWGaZVeVfYLrfOdDAothWcur5i05DoL3uOA0bRtV+QCuI6hALrt+tLj1BBdcYZaEgAZCLGZB2F1DFVJJRP+I2AKJdi81AnzOQD7PvvbAROLWuuHVYtnSETAeeYa56oP5nvd+q/P5wDc207FmHFZk412q8BGJITRIDYRmNhr2N3pfLGW2L5PR4mCEnGEfhbvoZRORqhakZBdY5S/ROJo2wESW1HQOSZFOA5lsWxkDOocwv4wrb59LWiLlDaw="

matrix:
  include:
    - name: Project summary
      env: TWINCAT_SUMMARY=1
    - name: Pragma linting
      env: TWINCAT_PRAGMALINT=1
    - name: Documentation building
      env: TWINCAT_BUILD_DOCS=1

install:
  # Pull PCDS standard CI scripts 
  - git clone --depth 1 https://github.com/pcdshub/pcds-ci-helpers.git

script:
  # Execute pytmc summarizing, linting, and documentation building
  - source pcds-ci-helpers/travis/init.sh
